<?php

/**
 * @file
 * Supports Islandora submodule islandora_mirador.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function islandora_mirador_theme() {
  return [
    'mirador' => [
      'variables' => [
        'iiif_manifest_url' => NULL,
        'mirador_view_id' => NULL,
      ],
      'template' => 'mirador',
    ],
  ];
}

/**
 * Implements template_preprocess_*().
 */
function template_preprocess_mirador(&$variables) {
  $variables['mirador_view_id'] = Html::getUniqueId($variables['mirador_view_id']);
  $variables['#attached']['drupalSettings']['mirador_view_id'] = $variables['mirador_view_id'];
}

function islandora_mirador_library_info_alter(&$libraries, $extension) {
  if ($extension == 'islandora_mirador') {

    $config = \Drupal::service('config.factory')->get('islandora_mirador.settings');
    if ($config->get('mirador_library_use_remote') =='remote') {
      $libraries['mirador']['js'][$config->get('mirador_library_location')] = [
        'type' => 'external',
        'minified' => TRUE,
      ];
    }
    else {
      unset($libraries['mirador']['remote']);
      unset($libraries['mirador']['license']);
      $libraries['mirador']['js']['/libraries/mirador/dist/main.js'] = [];
    }
  }
}
