islandora_mirador.settings:
  type: config_object
  label: 'Mirador Settings'
  mapping:
    mirador_library_installation_type:
      type: string
      label: 'Mirador library use remote'
    mirador_enabled_plugins:
      type: sequence
      label: 'Enabled Plugins'
      sequence:
        type: string
        label: 'Plugin'
    iiif_manifest_url:
      type: string
      label: 'URL pattern for IIIF manifest view'
    mirador_library_minified:
      type: boolean
      label: 'Use minified Mirador library'
    mirador_language_support:
      type: boolean
      label: 'Enable language support'
    mirador_selected_theme:
      type: string
      label: 'Selected Mirador theme'
    mirador_theme_light_primary:
      type: string
      label: 'Light theme primary color'
    mirador_theme_light_secondary:
      type: string
      label: 'Light theme secondary color'
    mirador_theme_dark_primary:
      type: string
      label: 'Dark theme primary color'
    mirador_theme_dark_secondary:
      type: string
      label: 'Dark theme secondary color'
