<?php

/**
 * @file
 * Supports Islandora submodule islandora_mirador.
 */

/**
 * Implements hook_theme().
 */
function islandora_mirador_theme() {
  return [
    'miradordiv' => [
      'variables' => [
        'iiif_manifest_url' => NULL,
      ],
      'template' => 'miradordiv',
    ],
    'mirador' => [
      'variables' => [
        'iiif_manifest_url' => NULL,
      ],
      'template' => 'mirador',
    ],
  ];
}
